Always show ASan log

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -143,6 +143,7 @@ jobs:
           ECHO ::group::Test libcat
           REM note: 颜色是不可能有颜色的，只能等gtest做这个功能或者githubactions支持那两个WIN32API
           REM note: ^ yet impossible to add color, we can only wait for github actions support SetConsoleAttribute or gtest support unix color on windows
+          SET ASAN_OPTIONS=log_path=asan.log
           IF "Debug" == "${{ matrix.build-type }}" ( "C:\OpenCppCoverage\OpenCppCoverage.exe" ^
             --export_type cobertura:coverage.xml ^
             --sources include ^
@@ -156,10 +157,13 @@ jobs:
             --modules build\Debug\cat_tests.exe -- ^
             build\Debug\cat_tests.exe --gtest_color=yes || goto error ) ELSE (build\Release\cat_tests.exe --gtest_color=yes || goto error)
           ${{ matrix.build-type == 'Debug' && format('C:\Codecov\codecov -f coverage.xml -t {0}', secrets.CODECOV_TOKEN) || '' }}
+          ECHO ASan log:
+          TYPE asan.log* || REM
           ECHO ::endgroup::
           EXIT /b 0
           REM error condition
           :error
+          ECHO "::error::Test failed"
           EXIT /b %errorlevel%
 
   unix-tests:
@@ -211,12 +215,12 @@ jobs:
           cmake --build . -j --target cat_tests || exit 1
           echo "::endgroup::"
           echo "::group::Test libcat"
-          ASAN_OPTIONS=log_path=/tmp/asan.log ./cat_tests --gtest_color=yes || {
-            echo "::warning::Test failed"
-            echo "ASan log:"
-            cat /tmp/asan.log*
+          ASAN_OPTIONS=log_path=asan.log ./cat_tests --gtest_color=yes || {
+            echo "::error::Test failed"
             exit 1
           }
+          echo "ASan log:"
+          cat asan.log* || :
           echo "::endgroup::"
 
       - name: Coverage tests
